### ISSUE TITLE
Runtime error: Server is failing to create in the autograder

### ISSUE THREAD

**Issue by ineal23** [comp426-2023-spring/a01#10]
Delete text above this line before you submit your issue. Place your issue information in the appropriate sections below. 

#### What is happening?
I didn't see in the documentation anything about testing our server without submitting it to github. The server is failing to create in github according to my knowledge.

#### What does the error say is happening?
❌ Run server listening on randomly assigned port

#### What do you think the error means?
I think there is something wrong with my https server creation or possibly how I used the minimist module to assign const port.

#### Command string
--

#### Code snippet
--

#### Screenshots
<img width="877" alt="Screen Shot 2023-02-06 at 12 30 44 PM" src="https://user-images.githubusercontent.com/69776357/217042815-fd9ef3a1-27b8-4839-9eeb-b700a30da81b.png">

#### Error log
::error::Error: Exit with code: 7 and signal: null

#### Node.js version
v18.13.0

#### Operating system
Darwin isaiahs-mbp.wireless-1x.unc.edu 21.6.0 Darwin Kernel Version 21.6.0: Wed Aug 10 14:25:27 PDT 2022; root:xnu-8020.141.5~2/RELEASE_X86_64 x86_64

**Comment by daqichen** [comment]
@ineal23  Looking at the output from the autograder, it looks like it is due to the PORT 3000 being occupied, which sometimes happens to Mac users, you can try to set the default to 8080 instead of 3000.

```
Error: listen EADDRINUSE: address already in use :::3000
```

**Comment by ineal23** [comment]
When I changed to 8080, the autograder is still giving me similar errors.

**Comment by daqichen** [comment]
@ineal23 Upon further looking at your implementation of `server.js`, the way you are setting up your `server` const is a little strange, can you follow [this example](https://www.w3schools.com/nodejs/met_http_createserver.asp) of the `http.createServer` method?

**Comment by ineal23** [comment]
<img width="691" alt="Screen Shot 2023-02-08 at 12 50 15 PM" src="https://user-images.githubusercontent.com/69776357/217612773-82115007-244c-431a-8817-262a617121cf.png">

The implementation of that example is a bit weird to me since the comments list the 3 things that need to be included within the http function.

**Comment by daqichen** [comment]
@ineal23 For Mac, 5555 port should be fine but 3000 is not available. See if that fixes it.

**Comment by ineal23** [comment]
I got it sorted out in office hours. Thanks for the help!
