### ISSUE TITLE
Missing info: a01 Node.js links invalid

### ISSUE THREAD

**Issue by YinuoLiu0708** [comp426-2023-spring/a01#3]
#### URL of file with the missing/incorrect info
https://github.com/comp426-2023-spring/a01

#### Line number with missing or incorrect info
a0 1 Readme Instruction part

#### What is wrong?
The links directing to Node.js learning pages are all invalid.

**Comment by jdmar3** [comment]
This is a duplicate of #2. I will follow up there.
