### ISSUE TITLE
Missing/incorrect info: Most of nodejs links still lead to "page not found"

### ISSUE THREAD

**Issue by tanatc1256** [comp426-2023-spring/a01#5]
#### URL of file with the missing/incorrect info
https://github.com/comp426-2023-spring/a01

#### Line number with missing or incorrect info
296, 300, 323, 338, 348

#### What is wrong?
The following links lead to "page not found"
https://nodejs.dev/en/learn/build-an-http-server
https://nodejs.dev/en/learn/the-nodejs-http-module
https://nodejs.dev/en/learn/the-nodejs-fs-module
https://nodejs.dev/en/learn/error-handling-in-nodejs
https://nodejs.dev/en/learn/nodejs-accept-arguments-from-the-command-line

#### What should be there instead?
Links that lead to the right source of information needed to complete the assignment

**Comment by jdmar3** [comment]
Linked to #2. I'm running down where this information is now and will update this issue as I find it.

**Comment by jdmar3** [comment]
Alright, all URLs have been updated and checked. Some of the previous resources were altered and are no longer on their own standalone pages. In those cases, I updated the links to point to a set of documentation rather than a single page.

**Comment by jdmar3** [comment]
Also, you can grab the new file from the template repo and the links will all be updated: https://raw.githubusercontent.com/comp426-2023-spring/a01/main/README.md

If you want to do that directly in your local repo to make things easy, `cd` into your local repo directory for a01 and then run:

```
curl https://raw.githubusercontent.com/comp426-2023-spring/a01/main/README.md -o README.md
```

That will replace the old version with the new one and then you can commit and push it and you'll have updated it.
