### ISSUE TITLE
Having trouble making .gitignore file

### ISSUE THREAD

**Issue by azaria-p** [comp426-2023-spring/a01#6]
#### Description
Trying to make the .gitignore file in command prompt

#### Screenshots
<img width="548" alt="image" src="https://user-images.githubusercontent.com/84456426/214655802-1d1129d8-b827-426f-ae7e-99836a1ea242.png">

#### Steps to reproduce
CD into correct directory, try and make .gitignore file.

**Comment by jesse-wei** [comment]
Dotfiles beginning with `.` are hidden and will not show up unless you apply the `-a` flag. Try `ls -a`.

**Comment by jdmar3** [comment]
@jesse-wei is 100% correct here.

Also, git will not read `.gitignore.txt`. The file has to be named `.gitignore` specifically. If you want a full example, look at the long gitignore file that it linked from the instructions. That has everything that you would probably want, at baseline, for git to ignore in a Node project.

Another way to see what is in such a file is to open it with vim: 

```
vim .gitignore
```

Or just read its contents out to STDOUT:

```
cat .gitignore
```
