### ISSUE TITLE
Adding rows to HTML table

### ISSUE THREAD

**Issue by ineal23** [comp426-2023-spring/a01#7]
Delete text above this line before you submit your issue. Place your issue information in the appropriate sections below. 

#### What is happening?
I am having trouble adding rows to the html table given.

#### What does the error say is happening?
No errors as no code has been ran.

#### What do you think the error means?
--

#### Command string
--

#### Code snippet
--

#### Screenshots
--

#### Node.js version
v18.13.0

#### Operating system
Darwin isaiahs-mbp.wireless-1x.unc.edu 21.6.0 Darwin Kernel Version 21.6.0: Wed Aug 10 14:25:27 PDT 2022; root:xnu-8020.141.5~2/RELEASE_X86_64 x86_64

**Comment by daqichen** [comment]
Are you following this format?

```html
<tbody>
  	<tr>
    		<td>A</td><td></td>
  	</tr>
  	<tr>
    		<td></td><td>B</td>
  	</tr>
  	<tr>
    		<td></td><td>C</td>
  	</tr>
  	<tr>
    		<td></td><td>D</td>
  	</tr>
  	<tr>
    		<td>E</td><td></td>
  	</tr>
  	<tr>
    		<td>F</td><td></td>
  	</tr>
  	<tr>
    		<td></td><td>G</td>
  	</tr>
  	<tr>
    		<td>?</td><td>?</td>
  	</tr>
</tbody>
```

**Comment by daqichen** [comment]
Resolved during Office Hour, Closing issue now.
