### ISSUE TITLE
Trouble implementing the minimist module

### ISSUE THREAD

**Issue by ineal23** [comp426-2023-spring/a01#9]
***Delete text above this line before you submit your issue. Place your issue information in the appropriate sections below.***

#### Description
I am having trouble understanding the documentation to implement the minimist module.

#### Screenshots
--

#### File (link)
--

#### Steps to reproduce
--

#### Steps to resolve
--

**Comment by daqichen** [comment]
@ineal23 You will find a comprehensive documentation here: https://openbase.com/js/minimist

Please detail any specific questions regarding `minimist` you have in followups so we can help you with specifically those questions.

**Comment by ineal23** [comment]
I had trouble implementing after reading the documentation where as the fs and https modules I processed more clearly. Such as this screenshot.
<img width="678" alt="Screen Shot 2023-02-03 at 2 10 09 PM" src="https://user-images.githubusercontent.com/69776357/216687259-d42d7431-82e0-405c-81d1-8f693b6867dc.png">

**Comment by daqichen** [comment]
@ineal23 
It's common to have trouble implementing some concepts even after reading the documentation. In your case, it sounds like you had a better understanding of the `fs` and `https` modules than the module that you had trouble with. To overcome this challenge, you can try a few things:

1. Experiment: Try experimenting with the module by following the tutorial at the link. This can help you gain a deeper understanding of the module's capabilities and limitations.

2. Find alternative resources: Try reading alternative resources, such as tutorials, blog posts, or video lessons, to see if they provide a different or clearer explanation of the module.

3. Watch Lecture Recording: Professor Martin does live-coding during lecture and uses `minimist` package extensively during those live-coding sessions. 

By employing these strategies, you can gain a better understanding of the module you are working with and overcome any challenges you may face when implementing it.

Again, if you are still having trouble, please specific what exactly you are confused about.
